package gui.prestamo;

import dataBase.dao.ClienteDAO;
import dataBase.dao.DPrestamoDAO;
import dataBase.dao.PrestamoDAO;
import java.awt.Toolkit;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import tools.UtilsTable;

/**
 *
 * @author Alfonso
 * Ventana que registra un prestamo de libros
 */
public class Prestamo extends javax.swing.JInternalFrame {
    int cliente_id;
    String empleado_id;
    String cliente_nombre;
    String empleado_nombre;
    Object[][] prestamos;
    // Para consultar los datos de la DB
    ClienteDAO cliente_dao;    
    PrestamoDAO prestamo_dao;
    // Ventana que agrega libros
    AddLibrosPrestamo addLibrosPrestamo;
    SelectCliente selectCliente;

    /**
     * Creates new form Libros
     * @param id_empleado
     * @param id_sucursal
     * @param empleado_nombre
     */
    public Prestamo(String id_empleado, String id_sucursal, String empleado_nombre) {
        initComponents();
        // se obtienen los datos del empkleado y tienda
        this.empleado_id = id_empleado;
        this.empleado_nombre = empleado_nombre;
        // pone el nombre del empleado
        lblEmpleadoIn.setText(this.empleado_nombre);
        
        DateTimeFormatter date_format = DateTimeFormatter.ofPattern("dd/MM/yyyy");                
        String today = date_format.format(LocalDateTime.now());
        lblFechaOut.setText(today);
        // Consulta los datos
        cliente_dao = new ClienteDAO();
        prestamo_dao = new PrestamoDAO();
        // crea instancia de las ventanas
        addLibrosPrestamo = new AddLibrosPrestamo(null, true);        
        selectCliente = new SelectCliente(null, true);
        // llena los datos
        LlenaDatos();
    }
    
    private void LlenaDatos(){
        LlenaTablaLibros();
        LlenaTablaPrestamos();
    }
    
    private void LlenaTablaLibros(){            
        int[][] cellAlignment = {{0,javax.swing.SwingConstants.LEFT, javax.swing.SwingConstants.RIGHT}};
        int[][] cellSize = {{0,0},
                            {1,700}};
        String[] T_PRESTAMO = {"","Título"};
        // llena la tabla 
        UtilsTable.llenaTabla(tableList, null, T_PRESTAMO, cellAlignment, cellSize);
        UtilsTable.quitarColumna(tableList, 0);        
    }
    
    private void LlenaTablaPrestamos() {
        prestamos = prestamo_dao.GetPrestamosByCliente(cliente_id);
        int[][] cellAlignment = {{0,javax.swing.SwingConstants.LEFT, javax.swing.SwingConstants.RIGHT}};
        int[][] cellSize = {{0, 460},
                            {1, 120},
                            {2, 120}};
        String[] T_PRESTAMO = {"Titulo", "Fecha Prestamo", "Fecha Vencimiento"};
        // llena la tabla 
        UtilsTable.llenaTabla(tableListPrestamos, prestamos, T_PRESTAMO, cellAlignment, cellSize);                  
    }
    
    // Valida si se llenaron los datos
    private boolean EstanLlenos(){        
        if (lblNombreCliente.getText().equals("Seleccione un cliente")){
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.", "Aviso", 2);
            
            return false;
        } else if (tableList.getRowCount() == 0){
            Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, "No hay libros en prestamo.", "Aviso", 2);
            return false;
        }        
        
        return true;
    }       
    
    private void CancelaEdit(){
        lblNombreCliente.setText("Seleccione un cliente");     
        lblFechaIn.setText("");
        UtilsTable.limpiaTabla(tableList);
        UtilsTable.limpiaTabla(tableListPrestamos);
    }
    
    private boolean VerificaRepetido(int idLibro) {
        for (int i = 0; i < tableList.getRowCount(); i++) {            
            if ((int) UtilsTable.obtenerValor(tableList, i, 0) == idLibro) {
                return false;
            }               
        }
        return true;
    }
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrestamo = new javax.swing.JPanel();
        btnGuarda = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblFechaOut = new javax.swing.JLabel();
        lblEmpleadoIn = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        lblFechaIn = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JLabel();
        btnCancela = new javax.swing.JButton();
        pnlTableList = new javax.swing.JPanel();
        scpTableList = new javax.swing.JScrollPane();
        tableList = new javax.swing.JTable();
        btnAddPelicula = new javax.swing.JButton();
        btnBorrarPel = new javax.swing.JButton();
        pnlTableListPrestamos = new javax.swing.JPanel();
        scpTableList1 = new javax.swing.JScrollPane();
        tableListPrestamos = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Prestamo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestamo_libro.png"))); // NOI18N
        setName(""); // NOI18N

        pnlPrestamo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        pnlPrestamo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/guardar.png"))); // NOI18N
        btnGuarda.setToolTipText("Guardar prestamo");
        btnGuarda.setFocusable(false);
        btnGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaActionPerformed(evt);
            }
        });
        pnlPrestamo.add(btnGuarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 40, 40));

        lblCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCliente.setText("Cliente");
        pnlPrestamo.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        lblFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFecha.setText("Fecha:");
        pnlPrestamo.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, 20));

        lblEmpleado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEmpleado.setText("Empleado:");
        pnlPrestamo.add(lblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 20));

        lblFechaOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlPrestamo.add(lblFechaOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 190, 20));

        lblEmpleadoIn.setAlignmentX(0.5F);
        lblEmpleadoIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlPrestamo.add(lblEmpleadoIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 280, 20));

        lblEntrega.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEntrega.setText("Entrega:");
        pnlPrestamo.add(lblEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 20));

        lblFechaIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFechaIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlPrestamo.add(lblFechaIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 190, 20));

        lblNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCliente.setText("Seleccione un cliente");
        lblNombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblNombreCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNombreClienteMouseClicked(evt);
            }
        });
        pnlPrestamo.add(lblNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 280, 20));

        btnCancela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/cancelar.png"))); // NOI18N
        btnCancela.setToolTipText("Cancela prestamo");
        btnCancela.setFocusable(false);
        btnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaActionPerformed(evt);
            }
        });
        pnlPrestamo.add(btnCancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 40, 40));

        pnlTableList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle de prestamo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        pnlTableList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scpTableList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scpTableList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableListMouseExited(evt);
            }
        });
        tableList.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tableListComponentMoved(evt);
            }
        });
        scpTableList.setViewportView(tableList);

        pnlTableList.add(scpTableList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 120));

        btnAddPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/add.png"))); // NOI18N
        btnAddPelicula.setToolTipText("Agregar libro");
        btnAddPelicula.setFocusable(false);
        btnAddPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPeliculaActionPerformed(evt);
            }
        });
        pnlTableList.add(btnAddPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 40, 40));
        btnAddPelicula.getAccessibleContext().setAccessibleDescription("Agregar libros");

        btnBorrarPel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/borrar.png"))); // NOI18N
        btnBorrarPel.setToolTipText("Borrar libro");
        btnBorrarPel.setFocusable(false);
        btnBorrarPel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarPelActionPerformed(evt);
            }
        });
        pnlTableList.add(btnBorrarPel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 40, 40));

        pnlTableListPrestamos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prestamos del cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        pnlTableListPrestamos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scpTableList1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scpTableList1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableListPrestamos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableListPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableListPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListPrestamosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableListPrestamosMouseExited(evt);
            }
        });
        tableListPrestamos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tableListPrestamosComponentMoved(evt);
            }
        });
        scpTableList1.setViewportView(tableListPrestamos);

        pnlTableListPrestamos.add(scpTableList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 710, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTableList, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlTableListPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTableList, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTableListPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaActionPerformed
//         Guarda y actualiza los datos
        if (EstanLlenos()){
            // Guarda datos de los controles en un arreglo de objetos
            Object[] prestamo = new Object[4];
            prestamo[0] = lblFechaOut.getText();
            prestamo[1] = lblFechaIn.getText();
            prestamo[2] = cliente_id;
            prestamo[3] = empleado_id;
            // Guarda la prestamo y recupera el id            
            int prestamo_id = prestamo_dao.SavePrestamo(prestamo);
            if(prestamo_id != 0) {        
                // si guardo el prestamo, guarda los datos del detalle
                DPrestamoDAO daoDPrestamo = new DPrestamoDAO();
                int i;
                for (i = 0; i < tableList.getRowCount(); i++) {
                    int result = daoDPrestamo.saveDPrestamo(prestamo_id, (int) UtilsTable.obtenerValor(tableList, i, 0));
                    if(result == 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el detalle.", "Información", 1);
                        prestamo_dao.DeletePrestamo(prestamo_id);
                        break;
                    }
                }       
                if(i == tableList.getRowCount()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "El prestamo se guardó correctamente", "Información", 1);
                    CancelaEdit();
                }                
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar", "Información", 1);
            }                    
        }
    }//GEN-LAST:event_btnGuardaActionPerformed

    private void tableListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListMouseClicked
     
    }//GEN-LAST:event_tableListMouseClicked

    private void tableListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListMouseExited
    }//GEN-LAST:event_tableListMouseExited

    private void tableListComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableListComponentMoved
    }//GEN-LAST:event_tableListComponentMoved

    private void btnAddPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPeliculaActionPerformed
        if (tableList.getRowCount()== 3){
            // Suena un beep
            Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, "No se pueden agregar mas de 3\nlibros al prestamo.", "Aviso", 2);
        }
        else {
            // Abre la ventana para agregar libros
            // Localización de la ventana
            addLibrosPrestamo.setLocationRelativeTo(this);
            // hace visible la ventana
            addLibrosPrestamo.setVisible(true);
            // cuando cierra la ventana agrega el libro seleccionado a la tabla de detalle de prestamo
            // si selecciono un registro, pone el libro
            if (addLibrosPrestamo.tableList.getSelectedRow() >= 0){
                if (VerificaRepetido((int) addLibrosPrestamo.libro[0])) {
                    UtilsTable.agregarFila(tableList, addLibrosPrestamo.libro);                    
                    DateTimeFormatter date_format = DateTimeFormatter.ofPattern("dd/MM/yyyy");                
                    String fecha_entrega = date_format.format(LocalDateTime.now().plusDays(3 * tableList.getRowCount()));
                    lblFechaIn.setText(fecha_entrega);
                }
            }
        }
    }//GEN-LAST:event_btnAddPeliculaActionPerformed

    private void btnBorrarPelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarPelActionPerformed
        // Borrar peliucula del detalle
        // valida si selecciono la fila
        if (tableList.getSelectedRow() < 0){
            // Suena un beep
            Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila.","Aviso",2);
        }
        else{
            UtilsTable.quitarFila(tableList, tableList.getSelectedRow());
         }
    }//GEN-LAST:event_btnBorrarPelActionPerformed

    private void btnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaActionPerformed
        CancelaEdit();
    }//GEN-LAST:event_btnCancelaActionPerformed

    private void lblNombreClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreClienteMouseClicked
        if (evt.getClickCount() == 2){  
            // Abre la ventana para seleccionar usuario
            // Localización de la ventana
            selectCliente.setLocationRelativeTo(this);
            // hace visible la ventana
            selectCliente.setVisible(true);
            // cuando cierra la ventana agrega el libro seleccionado a la tabla de detalle de prestamo
            // si selecciono un registro, pone el libro
            cliente_id = selectCliente.cliente_id;
            LlenaTablaPrestamos();
            Object[] cliente_obj = cliente_dao.getClienteById(cliente_id);
            cliente_nombre = cliente_obj[1] + " " + cliente_obj[2] + " " + cliente_obj[3];
            lblNombreCliente.setText(cliente_nombre);
        }
    }//GEN-LAST:event_lblNombreClienteMouseClicked

    private void tableListPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListPrestamosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableListPrestamosMouseClicked

    private void tableListPrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListPrestamosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tableListPrestamosMouseExited

    private void tableListPrestamosComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tableListPrestamosComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tableListPrestamosComponentMoved

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPelicula;
    private javax.swing.JButton btnBorrarPel;
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnGuarda;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblEmpleadoIn;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaIn;
    private javax.swing.JLabel lblFechaOut;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JPanel pnlPrestamo;
    private javax.swing.JPanel pnlTableList;
    private javax.swing.JPanel pnlTableListPrestamos;
    private javax.swing.JScrollPane scpTableList;
    private javax.swing.JScrollPane scpTableList1;
    private javax.swing.JTable tableList;
    private javax.swing.JTable tableListPrestamos;
    // End of variables declaration//GEN-END:variables
}
