package gui.libro;

import dataBase.dao.EditorialDAO;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import tools.UtilsTable;

/**
 * Ventana que permite agregar Editoriales.
 * @author Alfonso 
 */
public class AddEditorial extends javax.swing.JDialog {
    String editorialId;
    EditorialDAO editorialDAO;

    // Para listar todos los editorial 
    Object[][] editorialesLista;
    java.awt.Frame parent;    

    /**
     * Creates new form AddEditorial.
     * @param parent ventana padre.
     * @param modal determina si la ventana no cede el foco a otra.
     */
    public AddEditorial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent= parent;
        setTitle("Editoriales");
       
        // Inicia los componentes.
        initComponents();
        editorialDAO = new EditorialDAO();
        llenaTabla();
    }
    
    /**
     * Establece el Id de la Editorial seleccionada
     * @param editorialId Id de la Editorial a editar.
     */
    public void setEditorialId(String editorialId) {   
        this.editorialId = editorialId;
        txtFiltro.setText("");
        llenaTabla();
    }
    
    /**
     * Llena y despliega la tabla de Editoriales.
     */
    private void llenaTabla() {     
        editorialesLista = editorialDAO.getEditorialByNombre(txtFiltro.getText().trim());
       
        // Titulos de la tabla
        String[] columnasNombre = {"","Editorial"};
       
        // Alineación de las celdas.
        int[][] cellAlignment = {{0,javax.swing.SwingConstants.LEFT}};
      
        // Tamaño de las celdas.
        int[][] cellSize = {{0, 0}, {1, 170}};
       
        UtilsTable.llenaTabla(cellAlignment, cellSize, columnasNombre, tblEditoriales, editorialesLista);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTableList = new javax.swing.JPanel();
        scpTableList = new javax.swing.JScrollPane();
        tblEditoriales = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        lblFiltro = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage( getClass().getResource("/img/prestamo_libro.png")));

        pnlTableList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        pnlTableList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scpTableList.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scpTableList.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblEditoriales.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblEditoriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scpTableList.setViewportView(tblEditoriales);

        pnlTableList.add(scpTableList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 170));

        txtFiltro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });
        pnlTableList.add(txtFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 25));

        lblFiltro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFiltro.setText("Filtrar:");
        pnlTableList.add(lblFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 25));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/add.png"))); // NOI18N
        btnNew.setToolTipText("Registrar nuevo actor");
        btnNew.setFocusable(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/borrar.png"))); // NOI18N
        btnDelete.setToolTipText("Borrar actor");
        btnDelete.setFocusable(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/editar.png"))); // NOI18N
        btnEdit.setToolTipText("Editar actor");
        btnEdit.setFocusable(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTableList, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTableList, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre una ventana que posibilida crear una Editorial.
     * @param evt evento que dispara la funcion.
     */
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        AddNewEditorial add_new_editorial = new AddNewEditorial(parent, true);        
        add_new_editorial.setLocationRelativeTo(this);
        add_new_editorial.setVisible(true);        
               
        // Cuando cierra la ventana agrega el actor a la tabla y lo selecciona.
        llenaTabla();
        UtilsTable.mueveTabla(UtilsTable.getRow(add_new_editorial.editorialId, editorialesLista), tblEditoriales);
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * Llena la tabla de Editoriales cada que se escribe una letra
     * @param evt evento que dispara la funcion.
     */
    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        llenaTabla();
    }//GEN-LAST:event_txtFiltroKeyReleased

    /**
     * Elimina a la Editorial seleccionado de la tabla de Editorial.
     * @param evt evento que dispara la funcion.
     */
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        // Si no selecciona fila, le avisa al usuario.
        if(tblEditoriales.getSelectedRow() < 0) {
            
            // Suena un beep y se muestra un mensaje.
            java.awt.Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila","Aviso", 2);
        } else {
            
            // Suena un beep y se muestra un mensaje de confirmacion.
            java.awt.Toolkit.getDefaultToolkit().beep();
            int res = javax.swing.JOptionPane.showConfirmDialog(this, "¿Eliminar " + editorialesLista[tblEditoriales.getSelectedRow()][1].toString() + "?",
                "Seleccione", JOptionPane.YES_NO_OPTION);
            
            // Si la respuesta es afirmativa, elimina el registro.
            if(res != 1) {
                String msj = "";                
                int ret = editorialDAO.deleteEditorial(tblEditoriales.getValueAt(tblEditoriales.getSelectedRow(), 0).toString());
                if(ret == 0) {
                    msj = "No se pudo eliminar por que tiene registros asignados.";
                    javax.swing.JOptionPane.showMessageDialog(this, msj, "Información", 1);
                }               
                
                // Reinicia controles y parametros.
                llenaTabla();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * Abre una ventana para poder editar al Editorial seleccionado.
     * @param evt evento que dispara la funcion.
     */
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(tblEditoriales.getSelectedRow() < 0) {
            
            // Suena un beep y se muestra un mensaje.
            Toolkit.getDefaultToolkit().beep();
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila", "Información", 1);
        } else {
            editorialId = tblEditoriales.getValueAt(tblEditoriales.getSelectedRow(), 0).toString();
            
            // Abre la ventana para editar.
            AddNewEditorial editEditorial = new AddNewEditorial(parent, true);
            editEditorial.setLocationRelativeTo(this);            
            editEditorial.setEditId(editorialId);
            editEditorial.setVisible(true);
            
            // Cuando cierra la ventana agrega la Editorial a la tabla y la selecciona.
            llenaTabla();
            UtilsTable.mueveTabla(UtilsTable.getRow(editEditorial.editorialId, editorialesLista), tblEditoriales);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JPanel pnlTableList;
    private javax.swing.JScrollPane scpTableList;
    private javax.swing.JTable tblEditoriales;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}