package gui.libro;

import dataBase.dao.IdiomaDAO;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 * Ventana que permite crear y editar Idiomas del catálogo
 * @author alfonso
 */
public class AddNewIdioma extends javax.swing.JDialog {
    int idiomaId;
    IdiomaDAO idiomaDAO;

    /**
     * Creates new form AddNewIdioma.
     * @param parent ventana padre.
     * @param modal determina si la ventana no cede el foco a otra.
     */
    public AddNewIdioma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        // Inicia los componentes.
        initComponents();
        processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        idiomaDAO = new IdiomaDAO();
        getRootPane().setDefaultButton(btnGuardar);                      
    }
    
    /**
     * Borra el texto
     */
    private void borrarTextos() {        
        txtIdioma.setText("");
    }
    
    /**
     * Establece el Id del Idioma a editar.
     * @param idiomaId Id del Idioma siendo editado.
     */
    public void setEditId(int idiomaId) {
        this.idiomaId = idiomaId;
        Object[] idioma_edit = idiomaDAO.getIdiomaById(idiomaId);
        
        // Muestra los datos en los controles
        txtIdioma.setText(idioma_edit[1].toString());        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTableList = new javax.swing.JPanel();
        txtIdioma = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Idioma");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage( getClass().getResource("/img/pen.png")));

        pnlTableList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        pnlTableList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIdioma.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlTableList.add(txtIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 140, 25));

        lblNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombre.setText("Idioma:");
        pnlTableList.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 25));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlTableList.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTableList, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTableList, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Crea un registro en la tabla Idioma con los datos proporcionados.
     * @param evt evento que dispara la funcion.
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(txtIdioma.getText().trim().length() == 0) {
            
            // Suena un beep y muestra un mensaje.
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Escriba el idioma", "Aviso", 2);
        } else {                      
            String idiomaNombre = txtIdioma.getText().trim();
            
            // Crear o actualizar un Idioma.
            if(idiomaId == 0) {
                idiomaId = idiomaDAO.saveIdioma(idiomaNombre);                
            } else {
                Object[] idiomaObj = new Object[2];
                idiomaObj[0] = idiomaId;
                idiomaObj[1] = idiomaNombre;
                idiomaId = idiomaDAO.updateIdioma(idiomaObj);                
            }
            
            if(idiomaId == 0) {
                
                // Suena un beep y muestra un mensaje de erro.
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Error al guardar el idioma", "Error", 0);                
            } else {
                borrarTextos();
                dispose();
            }            
        }  
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlTableList;
    private javax.swing.JTextField txtIdioma;
    // End of variables declaration//GEN-END:variables
}