package gui.clientes;

import dataBase.dao.EscolaridadDAO;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 * Ventana encargada de agregar y editar Escolaridades.
 * @author alfonso
 */
public class AddNewEscolaridad extends javax.swing.JDialog {
    int escolaridadId;
    EscolaridadDAO escolaridadDAO;

    /**
     * Creates new form AddNewEscolaridad.
     * @param parent ventana padre.
     * @param modal determina si la ventana no cede el foco a otra.
     */
    public AddNewEscolaridad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        // Inicia los componentes.
        initComponents();
        processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        
        // Crea el dao para acceder a la tabla Escolaridad.
        escolaridadDAO = new EscolaridadDAO();
        getRootPane().setDefaultButton(btnGuardar);                      
    }
    
    /**
     * Borra el texto.
     */
    private void borrarTextos() {
        txtEscolaridad.setText("");
    }
    
    /**
     * Asignar el Id de la Escolaridad siendo editada.
     * @param escolaridadId Id de la escolaridad siendo editada.
     */
    public void setEditId(int escolaridadId) {
        this.escolaridadId = escolaridadId;
        Object[] escolaridadEdit = escolaridadDAO.getEscolaridadById(escolaridadId);
        
        // Muestra los datos en los controles.
        txtEscolaridad.setText(escolaridadEdit[1].toString());        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTableList = new javax.swing.JPanel();
        txtEscolaridad = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pais");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage( getClass().getResource("/img/user_icon.png")));

        pnlTableList.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        pnlTableList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEscolaridad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlTableList.add(txtEscolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, 25));

        lblNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNombre.setText("Escolaridad:");
        pnlTableList.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 25));

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/guardar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlTableList.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTableList, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTableList, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Guarda la informacion introducida en la base de datos.
     * @param evt evento que dispara la funcion.
     */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(txtEscolaridad.getText().trim().length() == 0) {
          
            // Suena un beep.
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(this, "Escriba la Escolaridad", "Aviso", 2);
        } else {                      
            String escolaridadNombre = txtEscolaridad.getText().trim();
            if(escolaridadId == 0) {
                escolaridadId = escolaridadDAO.saveEscolaridad(escolaridadNombre);                
            } else {
                Object[] escolaridad = new Object[2];
                escolaridad[0] = escolaridadId;
                escolaridad[1] = escolaridadNombre;
                escolaridadId = escolaridadDAO.updateEscolaridad(escolaridad);                
            }
            
            if(escolaridadId == 0) {
               
                // Suena un beep.
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "Error al guardar la escolaridad", "Error", 0);                
            } else {
                borrarTextos();
                dispose();
            }            
        }  
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlTableList;
    private javax.swing.JTextField txtEscolaridad;
    // End of variables declaration//GEN-END:variables
}