package gui.clientes;


/**
 *
 * @author Carlos
 * Ventana que registra una renta de peliculas
 */
public class Clientes extends javax.swing.JInternalFrame {
  
    public Clientes(String idEmpleado, String idTienda, String empleadoName) {
        initComponents();
        
    }

    public Clientes() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRenta = new javax.swing.JPanel();
        btnGuarda = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        lblTotal2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtTitulo1 = new javax.swing.JTextField();
        txtTitulo2 = new javax.swing.JTextField();
        txtTitulo3 = new javax.swing.JTextField();
        txtTitulo4 = new javax.swing.JTextField();
        txtTitulo5 = new javax.swing.JTextField();
        txtTitulo6 = new javax.swing.JTextField();
        txtTitulo7 = new javax.swing.JTextField();
        txtTitulo8 = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actor.png"))); // NOI18N
        setName(""); // NOI18N

        pnlRenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N
        pnlRenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acciones/guardar.png"))); // NOI18N
        btnGuarda.setToolTipText("Guardaer renta");
        btnGuarda.setFocusable(false);
        btnGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaActionPerformed(evt);
            }
        });
        pnlRenta.add(btnGuarda, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 60, 60));

        lblCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCliente.setText("Nombre:");
        pnlRenta.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, 20));

        lblFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFecha.setText("Apellido Paterno:");
        pnlRenta.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, 20));

        lblTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotal.setText("Alcaldia:");
        pnlRenta.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 20));

        lblTotal1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotal1.setText("Apellido Materno:");
        pnlRenta.add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 20));

        lblTotal2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTotal2.setText("Correo:");
        pnlRenta.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, 20));

        jLabel1.setText("CP:");
        pnlRenta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        jLabel2.setText("Calle:");
        pnlRenta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel3.setText("No. Exterior:");
        pnlRenta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel4.setText("No. Interior:");
        pnlRenta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        txtTitulo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 250, 20));

        txtTitulo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 250, 20));

        txtTitulo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 250, 20));

        txtTitulo3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 250, 20));

        txtTitulo4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 250, 20));

        txtTitulo5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 250, 20));

        txtTitulo6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 250, 20));

        txtTitulo7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 250, 20));

        txtTitulo8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pnlRenta.add(txtTitulo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRenta, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRenta, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );

        pnlRenta.getAccessibleContext().setAccessibleName("Clientes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaActionPerformed
//         Guarda y actualiza los datos
        
    }//GEN-LAST:event_btnGuardaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuarda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JPanel pnlRenta;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTitulo1;
    private javax.swing.JTextField txtTitulo2;
    private javax.swing.JTextField txtTitulo3;
    private javax.swing.JTextField txtTitulo4;
    private javax.swing.JTextField txtTitulo5;
    private javax.swing.JTextField txtTitulo6;
    private javax.swing.JTextField txtTitulo7;
    private javax.swing.JTextField txtTitulo8;
    // End of variables declaration//GEN-END:variables
}
